### ISSUE TITLE
Implementation of convergence profile

### ISSUE THREAD

**Issue by nkhadka21** [aymgal/COOLEST#59]
Hi,
I am trying to use lenstronomy coolest interface to update coolest_template.json file from lenstronomy kwargs. I am doing this in SLSim (https://github.com/LSST-strong-lensing/slsim) where we have used elliptical power law, shear, and convergence for the lens model. So, we need a convergence profile  in coolest. However, I think currently  it is not implemented in the coolest. It would be great if you could implement it.

Thank you!

**Comment by aymgal** [comment]
Thanks @nkhadka21 for opening this issue! I'd like to get more information about the convergence profile, in order to know what would be the minimal set of parameters that are needed to describe it. I would imagine the storage of the convergence as a 2D array in a FITS file, similar to what is currently done for pixelated light models.

**Comment by nkhadka21** [comment]
Hi @aymgal , thank you for your response. We need a constant convergence sheet which is kappa= constant value and ra and dec at (0, 0) of the coordinate system.

**Comment by aymgal** [comment]
Hi @nkhadka21 , I just pushed PR #60 that adds a new `'ConvergenceSheet'` profile. Let me know if this is what you were looking for, and if so, please close this issue. Thanks!

**Comment by nkhadka21** [comment]
Thank you very much @aymgal !
